### ISSUE TITLE
thanks for the credentials

### ISSUE THREAD

**Issue by Schmenn** [Signature-Dom/Javascript-discord-bot#2]
# look at your database in mongoDB compass

https://github.com/Signature-Dom/Javascript-discord-bot/blob/f8de43f5792b94152ba5ccbc21efa81bb75ef6df/index.js#L17

## unblock me tho I'm sure you have questions

**Comment by Signature-Dom** [comment]
ive unblocked u but i dont use mongoDB compass its mongoDB atlas
